version: "3"

networks:
  example_network:

services:
  php:
    container_name: laravel_api_php
    build: ./docker/php
    volumes:
      - ./src:/var/www
    networks:
      - example_network

  nginx:
    container_name: laravel_api_nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - example_network

  db:
    container_name: laravel_api_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "application"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - example_network

  redis:
    image: "redis:latest"
    container_name: laravel_api_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "./docker/redis:/data"
    networks:
      - example_network
